app/api/urls.py
from .persons.views import PersonViewSet
from rest_framework.routers import DefaultRouter
from django.urls import path, include
from api.User.view_user import UserViewSet, Login, Logout


router = DefaultRouter()

router.register(r'Person', PersonViewSet, basename='Person')
# router.register(r'Person-adjudicacion', PersonViewSetAdjudicacion, basename='Person_adjudicacion')

router.register(r'UsersApi', UserViewSet, basename='UsersApi')

urlpatterns = [

    path('', include(router.urls), name="ViewApi"),
     path('Login/', Login.as_view(), name="Login"),
    path('Logout/', Logout.as_view(), name="Logout"),
    
]

app/app/urls.py
from django.contrib import admin
from django.urls import path, include


from django.conf import settings
from django.conf.urls.static import static

from django.conf.urls import handler404, handler500
from core.startpage.views import Error404, Error500
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('core.login.urls'), name='login'),
    path('home/', include('core.startpage.urls'), name='home'),
    path('users/', include('core.users.urls'), name='user'),
    path('report/', include('core.report.urls'), name='report'),


    # api
    path('api/', include('api.urls'), name='api'),

    #   TOKEN API
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),


]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404=Error404.as_view()
handler500=Error500.as_view()

app/core/startpage/urls.py
from django.urls import path, include
from .views import *


urlpatterns = [
    path('', Home.as_view(), name='home'),
    path('import/', import_files, name='import'),
    

    path('list_persons/', TemplateListPersons.as_view(), name='list_persons'),

    path('deudores/',deudores, name='deudores'),
    path('no-deudores/',noDeudoras, name='no_deudores'),
    path('total_usuarios/',total_usuarios, name='total_usuarios'),
    path('eliminar/',eliminar, name='eliminar_usuarios'),

    

]

app/core/users/urls.py
from django.urls import path
from core.users.views import listarUsuarios,UserCreateView,UserUpdateView,DeleteView, cambiarPass

app_name = 'users'

urlpatterns = [
    # user

    path('usuario/list-user/', listarUsuarios.as_view(), name='user_list'),
    path('usuario/add-user/', UserCreateView.as_view(), name='user_create'),
    path('usuario/update-user/<int:pk>/', UserUpdateView.as_view(), name='user_update'),
    path('usuario/delete-user/<int:pk>/', DeleteView.as_view(), name='user_delete'),

    path('cambiar/', cambiarPass, name='cambiarPass')

]

app/core/startpage/models.py
from decimal import Decimal
from django.db import models
from core.users.models import User



class Person(models.Model):
    anio_tit=models.IntegerField(default=0, null=True, blank=True)
    num_reg=models.IntegerField(default=0, null=True, blank=True)
    RUC=models.CharField(max_length=15,default='', null=True, blank=True)
    nombrecomercial=models.CharField(max_length=500,default='', null=True, blank=True)
    razonsocial=models.CharField(max_length=100,default='', null=True, blank=True)
    calleprincipal=models.CharField(max_length=50,default='', null=True, blank=True)
    numerocasa=models.CharField(max_length=50,default='', null=True, blank=True)
    callesecundaria=models.CharField(max_length=50,default='', null=True, blank=True)
    sector=models.CharField(max_length=50,default='', null=True, blank=True)
    patrimonio=models.CharField(max_length=100, default='', null=True, blank=True)
    ced_ruc_representante=models.CharField(max_length=13,default='', null=True, blank=True)
    nombrerepresentante=models.CharField(max_length=200,default='', null=True, blank=True)
    apellidorepresentante=models.CharField(max_length=200,default='', null=True, blank=True)
    negociotipo=models.CharField(max_length=200,default='', null=True, blank=True)
    describenegocio=models.CharField(max_length=2000,default='', null=True, blank=True)
    rubro_pagado=models.CharField(max_length=50,default='', null=True, blank=True)
    valorpagar=models.FloatField(null=True, blank=True)
    fechpago=models.CharField(max_length=50,default='', null=True, blank=True)
    estadotitulo=models.CharField(max_length=10,default='', null=True, blank=True)
    fecharuc=models.CharField(max_length=50,default='', null=True, blank=True)
    fecharegmunicipio=models.CharField(max_length=50,default='', null=True, blank=True)
    abiertocerrado=models.CharField(max_length=10,default='', null=True, blank=True)
    fechacierre=models.CharField(max_length=50,default='', null=True, blank=True)
    canton_ruc=models.CharField(max_length=20,default='', null=True, blank=True)
    provincia_ruc=models.CharField(max_length=50,default=False)
    x=models.CharField(max_length=30,default='', null=True, blank=True)
    y=models.CharField(max_length=30,default='', null=True, blank=True)
    latitud=models.CharField(max_length=30,default='', null=True, blank=True)
    longitud=models.CharField(max_length=30,default='', null=True, blank=True)


    descripcion=models.TextField()


  

app/core/startpage/forms.py
from .models import *
from django import forms


from .models import *

class PersonRegistration(forms.ModelForm):
    class Meta:
        model = Person
        fields='__all__'

app/core/startpage/views.py
from multiprocessing import context
from django.http import HttpResponse
from django.shortcuts import render
from django.contrib import messages
from django.views.generic import ListView, TemplateView
from requests import Response
from .resources import PersonResource
from tablib import Dataset
from django.db.models import Q

from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt

from django.views.generic.base import TemplateView

from .models import *
from .forms import *
from core.users.models import User


# Create your views here.
class TemplateListPersons(TemplateView):
    template_name = "datatable/table.html"

    @method_decorator(csrf_exempt)
    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Listado de usuarios'
        return context


class Home(TemplateView):
    template_name = "index.html"

    @method_decorator(csrf_exempt)
    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        person = Person.objects.all()
        person_deudore = Person.objects.filter(valorpagar__gte=50.0)
        person_no_deudore = Person.objects.filter(valorpagar__lt=20.0)
        users1 = User.objects.filter(is_superuser=0)
        context = super().get_context_data(**kwargs)
        context["title"] = "Panel inicio"
        context["person"] = person.count()
        context["person_deudor"] = person_deudore.count()
        context["person_no_deudore"] = person_no_deudore.count()
        context["users"] = users1.count()
        return context

#   IMPORT FILE EXCEL (XLS)


def import_files(request):

    try:
        if request.method == 'POST':
            person_resource = PersonResource()
            dataset = Dataset()
            new_person = request.FILES['myfile']

            if not (new_person.name.endswith('xls') or new_person.name.endswith('xlsx')):
                messages.info(request, 'FORMATO INCORRECTO')
                return render(request, 'index.html')

            imported_data = dataset.load(new_person.read(), format='xls')
            for data in imported_data:
                """ value=Person(
                    data[0],data[1],data[2],data[3],data[4],data[5],data[6],data[7],
                    data[8],data[9],data[10],data[11],data[12],data[13],data[14],data[15],
                    data[16],data[17]
                ) """

                persona = Person()
                persona.anio_tit = data[0]
                persona.num_reg = int(data[1])
                persona.RUC = data[2]
                persona.nombrecomercial = data[3]
                persona.razonsocial = data[4]
                persona.calleprincipal = data[5]
                persona.numerocasa = data[6]
                persona.callesecundaria = data[7]
                persona.sector = data[8]
                persona.patrimonio = data[9]
                persona.ced_ruc_representante = data[10]
                persona.nombrerepresentante = data[11]
                persona.apellidorepresentante = data[12]
                persona.negociotipo = data[13]
                persona.describenegocio = data[14]
                persona.rubro_pagado = data[15]
                persona.valorpagar = data[16]
                persona.fechpago = data[17]
                persona.estadotitulo = data[18]
                persona.fecharuc = data[19]
                persona.fecharegmunicipio = data[20]
                persona.abiertocerrado = data[21]
                persona.fechacierre = data[22]
                persona.canton_ruc = data[23]
                persona.provincia_ruc = data[24]
                persona.x = data[25]
                persona.y = data[26]
                persona.latitud = data[27]
                persona.longitud = data[28]
                # if data[27] == '' or data[28] == '':
                #     print('exito')

                persona.save()

            messages.success(request, "Datos cargados")
    except:
        messages.warning(request,"NO AH CARGADO NINGUN ARCHIVO")
        return render(request, 'index.html')
    return render(request, 'files/import.html', {'title': 'Importacion de datos'})


#   IMPORTED TIP OF DATA

def deudores(request):
    deudores = {
        'title':'PERSONAS DEUDORAS',
        'persons': Person.objects.filter(valorpagar__gte=50.0),
    }

    return render(request, 'files/import.html', deudores)

def noDeudoras(request):
    deudores = {
        'title':'PERSONAS DEUDORAS',
        'persons': Person.objects.filter(valorpagar__lte=50.0),
    }
    return render(request, 'files/import.html', deudores)

def total_usuarios(request):
    total = {
        'persons': Person.objects.all(),
        'title': 'LISTADO USUARIOS',
        'date_now': ''
    }
    return render(request, 'datatable/table.html', total)

def eliminar(request):
    persons=Person.objects.all()
    persons.delete()
    messages.warning(request,"USUARIOS ELIMINADOS")
    return render(request, 'index.html')

class Error404(TemplateView):
    template_name='startpage/404.html'

class Error500(TemplateView):
    template_name='startpage/500.html'

    @classmethod
    def as_error_view(cls):
        v=cls.as_view()
        def view(request):
            r=v(request)
            r.render()
            return r
        return view

app/templates/startpage/body.html
{% extends 'startpage/home.html' %} {% load static %} {% block head %}
<!--Block head of body-->
{% block head_body %}{% endblock %} {% endblock %} {% block body %}
<body class="hold-transition sidebar-mini layout-fixed">
  <div class="wrapper">
    <!--Include template header-->
    {% include 'startpage/header.html' %}
    <!--Include template sidebar-->
    {% include 'startpage/sidebar.html' %}
    <div class="content-wrapper">
      <!--Block breadcrumb-->
      <section class="content-header">
        <div class="container-fluid">
          <div class="row">
            <div class="col-sm-6"></div>
            <div class="col-sm-6">
              <!--Block breadcrumb-->
              {% block breadcrumb %}
              <ol class="breadcrumb float-right">
                <li class="breadcrumb-item">
                  <a href="#"><i class="fas fa-home"></i> Panel</a>
                </li>
                {% block breadcrumb_li %}

                <li class="breadcrumb-item active" aria-current="page">
                  <a href="{{ request.session.module.url }}">
                    <i class="{{ request.session.module.get_icon }}"></i> {{ title }} 
                  </a>
                </li>
                {% endblock %}
              </ol>
              {% endblock %}
            </div>
          </div>

          {% block details %} {% endblock %}
        </div>
      </section>
      <!--Block content-->
      <section class="content">
        <div class="container-fluid">{% block content %} {% endblock %}</div>
      </section>
    </div>
    <!--Include template footer-->
    {% include 'startpage/footer.html' %}
  </div>

  {% block script %}
  <script>
        {% if messages %}
            var html = '<p>';
            {% for message in messages %}
                html += '{{ message }}<br>';
            {% endfor %}
            html += '</p>';
            Swal.fire({
                title: 'Error!',
                html: html,
                icon: 'error'
            });
        {% endif %}
    </script>

  {% endblock %}
  
</body>
{% endblock %}

app/templates/startpage/delete.html
{% extends 'startpage/body.html' %} {% load widget_tweaks %} {% block details %}
<form method="post" action="." id="frmForm">
  <div class="card card-primary">
    <div class="card-header">
      <h3 class="card-title">
        <i class="fas fa-trash"></i>
        {{ title }}
      </h3>
    </div>
    <div class="card-body">
      {% csrf_token %}
      <input type="hidden" name="action" value="{{ action }}" />
      {% if form.errors %}
      <div class="alert alert-danger alert-dismissible">
        <button
          type="button"
          class="close"
          data-dismiss="alert"
          aria-hidden="true"
        >
          ×
        </button>
        <h5>
          <i class="icon fas fa-ban"></i> Ha ocurrido un error al querer guardar
          el registro
        </h5>
        <ul>
          {% for field in form %} {% for error in field.errors %}
          <li>{{ error }}</li>
          {% endfor %} {% endfor %}
        </ul>
      </div>
      {% endif %}
      <div class="alert alert-danger alert-dismissible">
        <h5><i class="icon fas fa-ban"></i> Notificación</h5>
        ¿Estas seguro de eliminar el registro N°{{ object.id }}?
      </div>
    </div>
    <div class="card-footer">
      <button type="submit" class="btn btn-primary btn-flat" id="btnBorrar">
        <i class="fas fa-save"></i> Si, aceptar
      </button>
      <a href="{{ user_list }}" class="btn btn-danger btn-flat">
        <i class="fas fa-times"></i> Cancelar
      </a>
    </div>
  </div>
</form>
<script>
  $("form").on("frmForm", function (e) {
    e.preventDefault();
    var parameters = new FormData(this);
    submit_with_ajax(
      window.location.pathname,
      "Notificación",
      "¿Estas seguro de eliminar el siguiente registro?",
      parameters,
      function () {
        Swal.fire({
          title: "Alerta",
          text: "Registro eliminado correctamente",
          icon: "success",
          timer: 2000,
          onClose: () => {
            location.href = "{{ user_list }}";
          },
        }).then((result) => {});
      }
    );
  });
</script>
{% endblock %}

app/templates/startpage/footer.html
{% load static %}

<footer class="main-footer">
    <div class="float-right d-none d-sm-block">
      <b>Version</b> 1.0
    </div>
    <strong>Copyright &copy; 2022 <a href="https://gadmuisne.gob.ec/web/">Muisne</a>.</strong> Derechos reservados.
  </footer>

app/templates/startpage/form.html
{% extends 'startpage/list.html' %}
{% load widget_tweaks %}
{% load static %}
{% block head_list %}
    <!--Formvalidation Libs-->
    <link rel="stylesheet" href="{% static 'lib/formvalidation-1.8.0/css/formValidation.min.css' %}">
    <script src="{% static 'lib/formvalidation-1.8.0/js/es6-shim.min.js' %}"></script>
    <script src="{% static 'lib/formvalidation-1.8.0/js/FormValidation.min.js' %}"></script>
    <script src="{% static 'lib/formvalidation-1.8.0/js/plugins/Bootstrap.min.js' %}"></script>
    <script src="{% static 'lib/formvalidation-1.8.0/js/locales/es_ES.min.js' %}"></script>
    <!--Block head form-->
    {% block head_form %}{% endblock %}
{% endblock %}

{% block content %}
    <form class="form" method="post" action="." enctype="multipart/form-data" id="frmForm"
          data-url="{{ list_url }}">
          
        <div class="card {{ dshboard.card }}">
            <div class="card-header">
                <h3 class="card-title">
                    {% if action == 'add' %}
                        <i class="fas fa-plus" aria-hidden="true"></i>
                    {% else %}
                        <i class="fas fa-edit" aria-hidden="true"></i>
                    {% endif %}
                    {{ title }}
                </h3>
                <div class="card-tools">
                    <small>Su último acceso al sistema fue el {{ request.user.last_login }}</small>
                </div>
            </div>
            <div class="card-body" style="display: block;">
                <div class="container-fluid">
                    <input type="hidden" name="action" id="action" value="{{ action }}">
                    {% csrf_token %}
                    {# Forms Visible #}
                    {% for field in form.visible_fields %}
                        <div class="form-group">
                            <label>{{ field.label }}:</label>
                                {{ field|add_class:'form-control'|attr:"autocomplete:off" }}
                        </div>
                    {% endfor %}
                </div>
            </div>
            {% block box_footer %}
                <div class="card-footer">

                    {% block buttons %}
                        <a href=" # " type="submit" class="btn btn-primary btn-flat">
                            <i class="fas fa-save" aria-hidden="true"></i> Guardar registro
                        </a>
                        <a href=" {% url 'users:user_list' %} " class="btn btn-danger btn-flat">
                            <i class="fas fa-times"></i> Cancelar
                        </a>
                    {% endblock %}

                </div>
            {% endblock %}
        </div>
    </form>
{% endblock %}

app/templates/startpage/header.html
{% load static %}

<!-- Navbar -->
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href=" {% url 'home' %} " class="nav-link">Home</a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="https://gadmuisne.gob.ec/web/" class="nav-link">Contact</a>
      </li>
    </ul>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">


      <!-- Messages Dropdown Menu -->
      <p><b>Acceso:</b> {{ request.user.last_login }} </p>

      <a class="nav-link" href=" {% url 'logout' %} ">
        <i class="fas fa-power-off"></i>
        
      </a>

        

      </li>
      <!-- Notifications Dropdown Menu -->

      <li class="nav-item">
        <a class="nav-link" data-widget="fullscreen" href="#" role="button">
          <i class="fas fa-expand-arrows-alt"></i>
        </a>
      </li>

    </ul>
  </nav>
  <!-- /.navbar -->

app/templates/startpage/home.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Panel adminsitrativo</title>
  <link rel="shortcut icon" href=" {% static 'img/default/muisne.jpg' %} ">

  <link rel="stylesheet" href="{% static 'lib/bootstrap-4.6.0/css/bootstrap.min.css' %}"/>
  <link rel="stylesheet" href="{% static 'lib/fontawesome-5.15.3/css/all.min.css' %}"/>
  <link rel="stylesheet" href="{% static 'lib/jquery-ui-1.12.1/jquery-ui.css' %}"/>
  <!--Javascript-->
  <script src="{% static 'lib/bootstrap-4.6.0/js/jquery.min.js' %}"></script>
  <script src="{% static 'lib/jquery-ui-1.12.1/jquery-ui.min.js' %}"></script>
  <script src="{% static 'lib/bootstrap-4.6.0/js/popper.min.js' %}"></script>
  <script src="{% static 'lib/bootstrap-4.6.0/js/bootstrap.min.js' %}"></script>
  <script src="{% static 'lib/bootstrap-4.6.0/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'lib/adminlte-3.1.0/js/adminlte.min.js' %}"></script>
  <!--Template-->
  <link rel="stylesheet" href="{% static 'lib/adminlte-3.1.0/css/adminlte.css' %}"/>
  <!--Styles-->
  <link rel="stylesheet" href="{% static 'css/style.css' %}"/>
  <!--Libs-->
  <script src="{% static 'lib/bootstrap-daterangepicker-3.1/js/moment.js' %}"></script>
  <script src="{% static 'lib/bootstrap-daterangepicker-3.1/js/moment-with-locales.js' %}"></script>
  <script src="{% static 'lib/jquery-confirm-3.3.4/jquery-confirm.min.js' %}"></script>
  <link rel="stylesheet" href="{% static 'lib/jquery-confirm-3.3.4/jquery-confirm.min.css' %}"/>
  <script src="{% static 'lib/sweetalert2-11.0.16/sweetalert2.all.min.js' %}"></script>
  <link rel="stylesheet" href="{% static 'lib/sweetalert2-11.0.16/sweetalert2.min.css' %}"/>
  <script src="{% static 'lib/jquery-loading-overlay-2.1.7/loadingoverlay.min.js' %}"></script>
  <script src="{% static 'js/functions.js' %}"></script>
  {% block head %}{% endblock %}

</head>
<body class="hold-transition sidebar-mini layout-navbar-fixed">
  {% block body %}

  {% endblock %}

  <script src="{% static 'js/main.js' %}"></script>

</body>


</html>

app/templates/startpage/list.html
{% extends 'startpage/body.html' %}
{% load static %}
{% block head_body %}
    <link rel="stylesheet" href="{% static 'lib/datatables-1.10.25/css/dataTables.bootstrap4.min.css' %}"/>
    <link rel="stylesheet" href="{% static 'lib/datatables-1.10.25/plugins/responsive-2.2.9/css/responsive.bootstrap4.min.css' %}"/>
{#    <link rel="stylesheet" href="{% static 'lib/datatables-1.10.20/css/jquery.dataTables.min.css' %}"/>#}
    <script src="{% static 'lib/datatables-1.10.25/js/jquery.dataTables.js' %}"></script>
    <script src="{% static 'lib/datatables-1.10.25/js/dataTables.bootstrap4.min.js' %}"></script>
    <script src="{% static 'lib/datatables-1.10.25/plugins/responsive-2.2.9/js/dataTables.responsive.min.js' %}"></script>
    <script src="{% static 'lib/datatables-1.10.25/plugins/responsive-2.2.9/js/responsive.bootstrap4.min.js' %}"></script>
    <!--Block head list-->
    {% block head_list %}{% endblock %}
{% endblock %}

{% block content %}
    <div class="card {{ dshboard.card }}">
        <div class="card-header">
            <h3 class="card-title">
                <i class="fas fa-search"></i>
                {{title}} | {{date_now}}
            </h3>
            <div class="card-tools">
                <small>Su último acceso al sistema fue el {{ request.user.last_login }}</small>
            </div>
        </div>
        <div class="card-body" style="display: block;">
            <div class="container-fluid">
                <!--Block content list-->
                {% block content_list %}
                    <!--Block content list before-->
                    {% block content_list_before %}
                        <br>
                    {% endblock %}

                    {% block options %}  {% endblock %}

                    <!--Table-->
                    <table width="100%" class="table table-bordered table-striped" id="data">
                        <thead>
                        <tr>
                            <!--Columns-->
                            {% block columns %}{% endblock %}
                        </tr>
                        </thead>
                        <tbody>
                        <!--Rows-->
                        {% block rows %}{% endblock %}


                        </tbody>
                    </table>
                {% endblock %}
            </div>
        </div>
        <!--Block box footer-->

        {% block box_footer %}
            <div class="card-footer">
                <!--Block box footer buttons-->
                {% block box_footer_buttons %}
                    {% if create_url %}
                        <a href=" {{ create_url }} " class="btn btn-primary btn-flat">
                            <i class="fas fa-plus"></i> Nuevo Registro
                        </a>
                    {% endif %}
                    <!--Block box footer add buttons-->
                    {% block box_footer_add_button %}{% endblock %}
                    <a href="{{ list_url }}" class="btn btn-success btn-flat">
                        <i class="fas fa-sync-alt"></i> Actualizar
                    </a>
                {% endblock %}
            </div>
        {% endblock %}
        <!--Block box footer after-->

        {% block box_footer_after %}{% endblock %}
    </div>
    {% block javascript_list %}
        <script type="application/javascript">
            var table;
            $(function () {
                table = $('#data').DataTable({
                    responsive: true,
                    autoWidth: false,
                    destroy: true,
                    initComplete: function (settings, json) {

                    }
                });

                $('.table')
                    .on('draw', function () {
                        $('[data-toggle="tooltip"]').tooltip();
                    })
                    .on('click', 'img', function () {
                        var src = $(this).attr('src');
                        load_image(src);
                    });
            });
        </script>
    {% endblock %}
{% endblock %}

app/templates/startpage/sidebar.html
{% load static %}
<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <a href="#" class="brand-link">
        <img src="{% static '/img/default/logo2.jpg' %}" alt="logo" class="img-circle" style="height: 36px;">
        <span class="brand-text font-weight-bold">Panel <i>Muisne</i> </span>
    </a>
    <div class="sidebar">
        <div class="user-panel mt-3 pb-3 mb-3 d-flex">
            <div class="image">
                {% if request.user.image  %}
                    <img src="{{ request.user.get_image }}" class="img-circle" style="height: 33.6px;" alt="User Image">
                {% else %}
                    <img src="{% static 'img/default/empty.png' %}" class="img-circle" style="height: 33.6px;" alt="User Image">
                {% endif %}
                
            </div>
            <div class="info">
                <a href="#" class="d-block">{{ request.user.get_short_name }}</a>
            </div>
        </div>
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                <li class="nav-header"><b>MODULOS</b></li>

                <li class="nav-item">
                    <a href=" {% url 'home' %} " class="nav-link">
                        <i class="fas fa-home"></i>
                        <p>
                            Inicio
                        </p>
                    </a>
                </li>

                {% if request.user.is_superuser %}
                <li class="nav-item">
                    <a href="{% url 'import' %}" class="nav-link">
                        <i class="fas fa-file-import"></i>
                        <p>
                            Importar
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href=" {% url 'list_persons' %} " class="nav-link">
                        <i class="fas fa-list"></i>
                        <p>
                            Listar
                        </p>
                    </a>
                </li>
                {% else %}
                
                <li class="nav-item">
                    <a href=" {% url 'list_persons' %} " class="nav-link">
                        <i class="fas fa-list"></i>
                        <p>
                            Listar
                        </p>
                    </a>
                </li>
                {% endif %}

                <li class="nav-item">
                    <a href=" {% url 'users:user_list' %} " class="nav-link">
                        <i class="fas fa-users-cog"></i>
                        <p>
                            Personal
                        </p>
                    </a>
                </li>

                <li class="nav-item">
                    <a href=" {% url 'ver_datos' %} " class="nav-link">
                        <i class="fas fa-file-excel"></i>
                        <p>
                            Reporte
                        </p>
                    </a>
                </li>


                {% if request.user.is_superuser %}
                <li class="nav-header"><b>ADMINISTRADOR</b></li>

                <li class="nav-item">
                    <a href="#" class="nav-link">
                        <i class="nav-icon fas fa-cogs"></i>
                        <p>
                            Configuraciones
                            <i class="right fas fa-angle-left"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a href=" # " class="nav-link">
                                <i class="fas fa-user-edit"></i>
                                <p>Editar perfil</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href=" {% url 'users:cambiarPass' %} " class="nav-link">
                                <i class="fas fa-key"></i>
                                <p>Cambiar contrasena</p>
                            </a>
                        </li>
                    </ul>
                </li>

                {% endif %}


            </ul>
        </nav>
    </div>
</aside>