app/api/urls.py
from .persons.views import PersonViewSet
from rest_framework.routers import DefaultRouter
from django.urls import path, include
from api.User.view_user import UserViewSet, Login, Logout


router = DefaultRouter()

router.register(r'Person', PersonViewSet, basename='Person')
# router.register(r'Person-adjudicacion', PersonViewSetAdjudicacion, basename='Person_adjudicacion')

router.register(r'UsersApi', UserViewSet, basename='UsersApi')

urlpatterns = [

    path('', include(router.urls), name="ViewApi"),
     path('Login/', Login.as_view(), name="Login"),
    path('Logout/', Logout.as_view(), name="Logout"),
    
]

app/app/urls.py
from django.contrib import admin
from django.urls import path, include


from django.conf import settings
from django.conf.urls.static import static

from django.conf.urls import handler404, handler500
from core.startpage.views import Error404, Error500
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('core.login.urls'), name='login'),
    path('home/', include('core.startpage.urls'), name='home'),
    path('users/', include('core.users.urls'), name='user'),
    path('report/', include('core.report.urls'), name='report'),


    # api
    path('api/', include('api.urls'), name='api'),

    #   TOKEN API
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),


]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404=Error404.as_view()
handler500=Error500.as_view()

app/core/users/urls.py
from django.urls import path
from core.users.views import listarUsuarios,UserCreateView,UserUpdateView,DeleteView, cambiarPass

app_name = 'users'

urlpatterns = [
    # user

    path('usuario/list-user/', listarUsuarios.as_view(), name='user_list'),
    path('usuario/add-user/', UserCreateView.as_view(), name='user_create'),
    path('usuario/update-user/<int:pk>/', UserUpdateView.as_view(), name='user_update'),
    path('usuario/delete-user/<int:pk>/', DeleteView.as_view(), name='user_delete'),

    path('cambiar/', cambiarPass, name='cambiarPass')

]

app/core/users/models.py
import requests
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.forms import model_to_dict
from app.settings import MEDIA_URL, STATIC_URL
from core.users.validators import *
import uuid
from app import settings
import os
from crum import get_current_request

class User(AbstractUser):
    image = models.ImageField(upload_to='users/%Y', null=True, blank=True)
    dni = models.CharField(max_length=10,  verbose_name='Cédula o RUC',validators=[vcedula])
    is_change_password = models.BooleanField(default=False)
    token = models.UUIDField(primary_key=False, editable=False, null=True, blank=True, default=uuid.uuid4, unique=True)
    
    def toJSON(self):
        item = model_to_dict(self, exclude=['last_login', 'token', 'password', 'user_permissions'])
        item['image'] = self.get_image()
        item['full_name'] = self.get_full_name()
        item['date_joined'] = self.date_joined.strftime('%Y-%m-%d')
        item['groups'] = self.get_groups()
        item['last_login'] = None if self.last_login is None else self.last_login.strftime('%Y-%m-%d')
        return item

    def generate_token(self):
        return uuid.uuid4()

    def get_image(self):
        if self.image:
            return '{}{}'.format(settings.MEDIA_URL, self.image)
        return '{}{}'.format(settings.STATIC_URL, 'img/default/empty.png')

    def remove_image(self):
        try:
            if self.image:
                os.remove(self.image.path)
        except:
            pass

    def delete(self, using=None, keep_parents=False):
        try:
            os.remove(self.image.path)
        except:
            pass
        super(User, self).delete()

    def get_groups(self):
        data = []
        for i in self.groups.all():
            data.append({'id': i.id, 'name': i.name})
        return data

    def get_group_id_session(self):
        try:
            request = get_current_request()
            return int(request.session['group'].id)
        except:
            return 0

    def set_group_session(self):
        try:
            request = get_current_request()
            groups = request.user.groups.all()
            if groups:
                if 'group' not in request.session:
                    request.session['group'] = groups[0]
                    request.session['infobyip'] = self.infobyip()
        except:
            pass

    def create_or_update_password(self, password):
        try:
            if self.pk is None:
                self.set_password(password)
            else:
                user = User.objects.get(pk=self.pk)
                if user.password != password:
                    self.set_password(password)
        except:
            pass

    def is_client(self):
        try:
            if hasattr(self, 'client'):
                return True
        except:
            pass
        return False

    def infobyip(self):
        response = {'ipaddress': '', 'location': '', 'isp': '', 'countrycode': ''}
        try:
            request = requests.get('https://wtfismyip.com/json').json()
            response = {
                'ipaddress': request['YourFuckingIPAddress'],
                'location': request['YourFuckingLocation'],
                'isp': request['YourFuckingISP'],
                'countrycode': request['YourFuckingCountryCode'],
            }
        except:
            pass
        return response

    def __str__(self):
        return self.get_full_name()

app/core/users/forms.py
from pyexpat import model
from crum import get_current_request
from django import forms
from django.contrib.auth import update_session_auth_hash
from django.forms import ModelForm

from .models import User


class UserForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['first_name'].widget.attrs['autofocus'] = True

    class Meta:
        model = User
        fields = 'first_name', 'last_name', 'username', 'password', 'dni', 'email', 'groups', 'image', 'is_active'
        widgets = {
            'first_name': forms.TextInput(attrs={'placeholder': 'Ingrese sus nombres'}),
            'image': forms.ClearableFileInput(attrs={'class': 'form-control-file mt-3'}),
            'last_name': forms.TextInput(attrs={'placeholder': 'Ingrese sus apellidos'}),
            'username': forms.TextInput(attrs={'placeholder': 'Ingrese un username'}),
            'dni': forms.TextInput(attrs={'placeholder': 'Ingrese su número de cedula'}),
            'email': forms.TextInput(attrs={'placeholder': 'Ingrese su correo electrónico'}),
            'password': forms.PasswordInput(render_value=True, attrs={'placeholder': 'Ingrese un password'}),
            'is_active': forms.CheckboxInput(attrs={'class': 'form-control-checkbox'})
        }
        exclude = ['is_change_password', 'is_staff', 'user_permissions', 'date_joined',
                   'last_login', 'is_superuser', 'token','groups']

    def update_session(self, user):
        request = get_current_request()
        if user == request.user:
            update_session_auth_hash(request, user)

    def save(self, commit=True):
        data = {}
        form = super()
        try:
            if form.is_valid():
                pwd = self.cleaned_data['password']
                u = form.save(commit=False)
                if u.pk is None:
                    u.set_password(pwd)
                else:
                    user = User.objects.get(pk=u.pk)
                    if user.password != pwd:
                        u.set_password(pwd)
                u.save()


                self.update_session(u)
            else:
                data['error'] = form.errors
        except Exception as e:
            data['error'] = str(e)
        return data

class UserEditForm(ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['first_name'].widget.attrs['autofocus'] = True

    class Meta:
        model = User
        fields = 'first_name', 'last_name', 'username', 'password', 'email', 'image', 'is_active'
        widgets = {
            'first_name': forms.TextInput(attrs={'readonly':True,'title':'No sepuede modificar'}),
            'last_name': forms.TextInput(attrs={'readonly':True,'title':'No sepuede modificar'}),
            'username': forms.TextInput(attrs={'placeholder': 'Ingrese un username'}),
            'dni': forms.TextInput(attrs={'readonly':True,'title':'No sepuede modificar'}),
            'email': forms.TextInput(attrs={'placeholder': 'Ingrese su correo electrónico'}),
            'password': forms.PasswordInput(render_value=True, attrs={'readonly':True,'title':'No sepuede modificar'}),
            'is_active': forms.CheckboxInput(attrs={'class': 'form-control-checkbox'})
        }
        exclude = ['is_change_password', 'is_staff', 'user_permissions', 'date_joined',
                   'last_login', 'is_superuser', 'token','groups']

    def update_session(self, user):
        request = get_current_request()
        if user == request.user:
            update_session_auth_hash(request, user)

    def save(self, commit=True):
        data = {}
        form = super()
        try:
            if form.is_valid():
                pwd = self.cleaned_data['password']
                u = form.save(commit=False)
                if u.pk is None:
                    u.set_password(pwd)
                else:
                    user = User.objects.get(pk=u.pk)
                    if user.password != pwd:
                        u.set_password(pwd)
                u.save()


                self.update_session(u)
            else:
                data['error'] = form.errors
        except Exception as e:
            data['error'] = str(e)
        return data

        ##  EDITAR
    

app/core/users/views.py
from django.urls import reverse_lazy
import json
from django.shortcuts import render

from django.http import JsonResponse, HttpResponse
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from core.startpage.models import Person

from core.users.forms import UserForm, UserEditForm
from core.users.models import User
from core.users.mixins import IsSuperuserMixin

from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt


class listarUsuarios(IsSuperuserMixin, ListView):
    model = User
    template_name = 'list_user.html'

    @method_decorator(csrf_exempt)
    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        person = User.objects.all().exclude(is_superuser=1)
        context = super().get_context_data(**kwargs)
        context['title'] = 'Listado de Notificadores'
        context['create_url'] = reverse_lazy('users:user_create')
        context['list_url'] = reverse_lazy('users:user_list')
        context['user']=person

        return context


class UserCreateView(CreateView):
    model = User
    template_name = 'create_user.html'
    form_class = UserForm
    success_url = reverse_lazy('users:user_list')

    @method_decorator(csrf_exempt)
    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)


    def validate_data(self):
        data = {'valid': True}
        try:
            type = self.request.POST['type']
            obj = self.request.POST['obj'].strip()
            if type == 'dni':
                if User.objects.filter(dni=obj):
                    data['valid'] = False
            elif type == 'username':
                if User.objects.filter(username__icontains=obj):
                    data['valid'] = False
            elif type == 'email':
                if User.objects.filter(email=obj):
                    data['valid'] = False
        except:
            pass
        return JsonResponse(data)

    def post(self, request, *args, **kwargs):
        data = {}
        action = request.POST['action']
        try:
            if action == 'add':
                data = self.get_form().save()
            elif action == 'validate_data':
                return self.validate_data()
            else:
                data['error'] = 'No ha seleccionado ninguna opción'
        except Exception as e:
            data['error'] = str(e)
        return HttpResponse(json.dumps(data), content_type='application/json')

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context['list_url'] = self.success_url
        context['title'] = 'Nuevo registro de un Usuario'
        context['action'] = 'add'
        return context


class UserUpdateView(UpdateView):
    model = User
    template_name = 'create_user.html'
    form_class = UserEditForm
    success_url = reverse_lazy('users:user_list')

    @method_decorator(csrf_exempt)
    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)


    def validate_data(self):
        data = {'valid': True}
        try:
            type = self.request.POST['type']
            obj = self.request.POST['obj'].strip()
            if type == 'username':
                if User.objects.filter(username__icontains=obj):
                    data['valid'] = False
            elif type == 'email':
                if User.objects.filter(email=obj):
                    data['valid'] = False
        except:
            pass
        return JsonResponse(data)

    def post(self, request, *args, **kwargs):
        data = {}
        action = request.POST['action']
        try:
            if action == 'add':
                data = self.get_form().save()
            elif action == 'validate_data':
                return self.validate_data()
            else:
                data['error'] = 'No ha seleccionado ninguna opción'
        except Exception as e:
            data['error'] = str(e)
        return HttpResponse(json.dumps(data), content_type='application/json')

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context['list_url'] = self.success_url
        context['title'] = 'Nuevo registro de un Usuario'
        context['action'] = 'add'
        return context


class DeleteView (DeleteView):
    model = User
    template_name = 'delete.html'
    success_url = reverse_lazy('users:user_list')
    url_redirect = success_url


    @method_decorator(csrf_exempt)
    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Eliminación de un Usuario'
        context['entity'] = 'Usuarios'
        context['list_url'] = self.success_url
        return context


def cambiarPass(request):
    return render(request,'changePassword.html')

app/core/users/templates/changePassword.html
{% extends 'startpage/form.html' %}
{% load static %}
{% load widget_tweaks %}
{% block head_form %}
    <script src="{% static 'lib/formvalidation-1.8.0/js/plugins/Tachyons.min.js' %}"></script>
    <script src="{% static 'lib/formvalidation-1.8.0/js/plugins/PasswordStrength.min.js' %}"></script>
    <script src="{% static 'lib/formvalidation-1.8.0/js/zxcvbn.js' %}"></script>
    <script src="{% static 'user/js/change_pwd.js' %}"></script>
{% endblock %}

{% block content %}
    <form class="form" method="post" action="." enctype="multipart/form-data" id="frmPassword"
          >
        <div class="card ">
            <div class="card-header">
                <h3 class="card-title">
                    <i class="fas fa-edit"></i>
                    {{ title }}
                </h3>
            </div>
            <div class="card-body" style="display: block;">
                <div class="container-fluid">
                    <input type="hidden" name="action" id="action" value="{{ action }}">
                    {% csrf_token %}
                    <div class="form-group row">
                        <label>Introduzca su password anterior:</label>
                        <div class="input-group my-group">
                            {{ form.old_password }}
                            <div class="input-group-append">
                                <button class="btn btn-primary btnShowPassword btn-flat" type="button">
                                    <i class="fas fa-eye"></i>
                                </button>
                            </div>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label>Ingrese su password:</label>
                        <div class="input-group my-group">
                            {{ form.new_password1 }}
                            <div class="input-group-append">
                                <button class="btn btn-primary btnShowPassword btn-flat" type="button">
                                    <i class="fas fa-eye"></i>
                                </button>
                            </div>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label>Repita su password:</label>
                        <div class="input-group my-group">
                            {{ form.new_password2 }}
                            <span class="input-group-btn">
                                            <a class="btn btn-primary my-group-button btnShowPassword btn-flat"
                                               type="button">
                                                <i class="fas fa-eye"></i>
                                            </a>
                                        </span>
                        </div>
                        <div class="progress password-progress">
                            <div id="strengthBar" class="progress-bar" role="progressbar"
                                 style="width: 0;"></div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="card-footer">
                <button type="submit" class="btn btn-primary btn-flat">
                    <i class="fas fa-save"></i> Cambiar password
                </button>
                <a href=" {% url 'home' %} " class="btn btn-danger btn-flat">
                    <i class="fas fa-times"></i> Cancelar
                </a>
            </div>
        </div>
    </form>
{% endblock %}

app/core/users/templates/create_user.html
{% extends 'startpage/form.html' %}
{% load static %}
{% block head_form %}
<script src="{% static 'lib/select2-4.0.13/js/select2.min.js' %}"></script>
    <script src="{% static 'lib/select2-4.0.13/js/i18n/es.js' %}"></script>
    <link rel="stylesheet" href="{% static 'lib/select2-4.0.13/css/select2.min.css' %}">
    <link rel="stylesheet" href="{% static 'lib/select2-4.0.13/css/select2-bootstrap4.min.css' %}">
    <script src="{% static 'user/js/form.js' %}"></script>


{% endblock %}

app/core/users/templates/delete.html
{% extends 'startpage/body.html' %}
{% load widget_tweaks %}
{% block head %}
    {% block head_form %}

    {% endblock %}
{% endblock %}
{% block content %}
    <form method="post" action="." enctype="multipart/form-data" id="frmForm">
        <div class="card card-dark">
            <div class="card-header">
                <h3 class="card-title">
                    {% if action == 'add' %}
                        <i class="fas fa-plus"></i>
                    {% else %}
                        <i class="fas fa-edit"></i>
                    {% endif %}

                    {{ title }}
                </h3>
            </div>
            <div class="card-body">
                {% csrf_token %}
                <input type="hidden" name="action" value="{{ action }}">
                {% if form.errors %}
                    <div class="alert alert-danger alert-dismissible">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
                        <h5><i class="icon fas fa-ban"></i> Ha ocurrido un error al querer guardar el registro</h5>
                        <ul>
                            {% for field in form %}
                                {% for error in field.errors %}
                                    <li>{{ error }}</li>
                                {% endfor %}
                            {% endfor %}
                        </ul>
                    </div>
                {% endif %}

                <div class="alert alert-danger alert-dismissible">
                    <h5> <i>Notificacion1</i> </h5>
                    <h4>Estas seguro de elimnar al Usuario {{ object.first_name }} </h4>
                </div>
                
            </div>
            <div class="card-footer">
                <button type="submit" class="btn btn-primary btn-flat">
                    <i class="fas fa-save"></i> Guardar registro
                </button>
                <a href="{% url 'users:user_list' %}" class="btn btn-danger btn-flat">
                    <i class="fas fa-times"></i> Cancelar
                </a>
            </div>
        </div>
    </form>

    <script>
        {% if form.errors %}
        var errores="";
            {% for field in form %}
                {% for error in field.errors %}
                    errores+='{{ error }}\n';
                    
                {% endfor %}
            {% endfor %}

            Swal.fire({
                icon: 'error',
                title: 'Oops...',
                text: errores,
                
            })  
        {% endif %}
    </script>

    
{% endblock %}

app/core/users/templates/list_user.html
{% extends 'startpage/list.html' %}
{% block columns %}

<th scope="col">CI</th>
<th scope="col">NOMBRES</th>
<th scope="col">APELLIDOS</th>
<th scope="col">USERNAME</th>
<th scope="col">EMAIL</th>
<th scope="col">FECHA REGISTRO</th>

<th scope="col">OPCIONES</th>
{% endblock %}
{% block rows %} 
    {% for i in user %}
    <tr>
        
        <td> {{i.dni}} </td>
        <td> {{i.first_name}} </td>
        <td> {{i.last_name}} </td>
        <td> {{i.username}} </td>
        <td> {{i.email}} </td>
        <td> {{i.date_joined}} </td>



        <td class=" d-flex justify-content-center" >
            <a href=" {% url 'users:user_update' i.id %} " class="btn btn-ms btn-success  "> <i class="fas fa-edit"></i> </a>
            <a href=" {% url 'users:user_delete' i.id %}  "  class="btn btn-ms btn-danger  "><i class="fas fa-ban"></i></a>
        </td>

    </tr>
    {% endfor %}


{% endblock %}